### ISSUE TITLE
Remove user defined mount resource

### ISSUE THREAD

**Issue by nyanpassu** [projecteru2/barrel#19]
Assume that a user had bind several directory to a container, that parent of those directory also belongs to the container:
```
 Mounts":[
{
"Type": "bind" ,
"Source": "/data/biz/cluster01/container01/data","Destination" : " /data/my_data" ,
"Mode" : "rw" ,
"RW" : true,
"Propagation" :"rprivate"
,
"Type" : "bind" ,
" Source" : " /data/biz/cluster01/container01/1og","Destination" : "/data/my_log",
"Mode" : "rw" ,
"RW":true,
"Propagation" :"rprivate"
],
```

The root directory for bindings of a single container is like "/data/biz/cluster01/container01", If user want to remove the directory, we need more info for us to conclude that the path is some sort of resource for the container. Thus we have plans:

A. User mount  /data/biz/cluster01/container01 as well
B. Recording the infomation in label:
```
"Labels": {
  “BARREL”: "{\"Mounts\: [\"/data/biz/cluster01/container01\"]"}"
}
```

For plan A, we need to parse the mounts to find out the directories need to remove and directories need not, and there will be a useless mount for the container. For plan B it's more simple but there is a risk that a container declares unrelated resources in the label, however we can do the same parsing to the mount declares inside label to eliminate the risk, or using a regex to safeguard it.

**Comment by CMGS** [comment]
why remove the source's parent dir?
no need
