### ISSUE TITLE
Design

### ISSUE THREAD

**Issue by CMGS** [projecteru2/barrel#2]
### 容器 with fixed IP label 
* Create -> docker -> minions 判断有这个 label 在另外一个地方存一个 flag -> 正常 assign IP 流程
* Stop -> docker -> minions 判断是否有 label
  * 没有 -> 正常释放
  * 有 -> 输出日志不释放
* Start -> docker -> minions 判断是否有 label
  * 没有 -> 正常 assign
  * 有 -> 从另外一个地方存的 flag 中取出 assign 的老 IP，返回给 docker
* Remove -> **barrel** -> docker
  * 有 label -> 清理 flag -> 正常 remove 行为转发给 docker

### 容器 without fixed IP label

一切照旧

#### old without fixed IP labels
* inherit network
  * get IP from old one 
  * old one stop -> 老流程，IP 释放回了 calico pool
  * minions 需要判断，不管有没有 fixed IP label，有则忽略 fixed IP label 逻辑，直接 assign 老 IP 出去。
  * start new one
    * succ -> remove old one
    * fail -> remove new one and start old one 

* no inherit network
  * old one stop -> 取决于老的是否带 label 带则走 minions 新流程，不带则走老流程
  * start new one
    * 不带 label -> 老流程
    * 带 label -> 新流程

#### old with fixed IP labels
* no inerit network
  * old one stop -> 新流程
  * start new one
    * 不带 label -> 老流程
    * 带 label -> 新流程

* inerit network
  * get IP from old one 
  * old one stop -> 新流程，这时候 IP 没释放回 calico pool
  * minions 需要判断，不管有没有 fixed IP label，有则忽略 fixed IP label 逻辑，并且在这里因为是 reserved IP 需要操作 calico IPAM 和 workload endpoints 使得能 IP 能 assign 出去。
    * start new one
    * succ -> remove old one -> **barrel** 删除 flag -> minions 需要对 IP 判断，如果存在另外一组 weps，则 minions 不把 IP 放回 calico pool。
    * fail -> remove new one -> IP 是配置中的，同样需要 minions 对 IP 判断，如果存在另外一组 weps，则 minions 不把 IP 放回 calico pool -> start old one -> 新流程

**Comment by CMGS** [comment]
对于 minions 来说

* 创建
  * 指定 IP -> 判断 IP 是否已经 assigned 是否有 weps
    * 有，reserved IP 直接二次 assign
    * 没有，老流程，池子里面抠出来
  * 未指定 IP
    * inspect 是否有 label ( 复用现有 label 处理流程不要新开 inspect 方法 )
      * 没有，老流程，池子里面抠一个
      * 有，新流程，抠一个并且其他位置写个 flag 并包含这个 IP
 
* 销毁，正常逻辑，reserved IP flag 会在 barrel 中销毁

**Comment by nyanpassu** [comment]
minions的实现：

- 固定IP的信息存储于etcd，key为/barrel/address/${ip}，value包含：
1. 使用该IP的容器ID
2. IP是否已经被分配（因为IP被IPAM Driver分配出去的时候获取不到容器ID，所以不能单纯使用容器ID作为是否被分配的标识）
2. 其他备用信息
- 容器信息，存储于etcd，key为/barrel/container/%{id}，value内包含：
1. 容器使用的IP地址信息

- RequestAddress
1. 判断是否申请特定IP，是则跳转3
2. 从calico IP池内分配IP，结束
3. 判断IP是否是已经被保留的IP，并跳转5
4. 判断IP是否已经被占用，否则把IP标识为已经被占用，并跳转5，是则抛出异常
5. 分配申请的特定IP

- Leave
1. 在Leave时通过docker api查找endpoint关联的container，判断container是否具有fixed-ip label，否则跳转3
2. 在etcd上记录该IP为固定IP（未占用状态），**并且在container下记录ip信息**（当前版本是在barrel inspect container里实现的，需要改在minions中）
3. 通过etcd判断该IP是否是固定IP，如果是则清除etcd下该IP的记录


barrel的实现：
- 其他请求照常转发，只hook RemoveContainer（把InspectContainer内的hook移除掉）
- RemoveContainer（以下hook在Remove Container之前之后皆可，使用goroutine执行，不干扰正常Remove流程）
1. 判断container是否在ETCD上有记录（不需要通过label来判断，查找etcd即可），否则结束
2. 根据container记录中的ip地址在etcd上查找是否有该固定ip的记录，否则结束
3. 查看该固定ip是否已经被分配，是则结束
4. 清除该固定ip的记录，然后通过calico api释放该ip（如果有并发的申请该ip的请求，那么并发请求可能会失败，但是不会产生数据异常情况，但是需要有log来记录行为，否则如果清除etcd记录后barrel crash，会导致ip无法被归还到calico ip池内。也可以先标记为已占用，然后释放该ip，然后清除这个ip记录）

**Comment by anrs** [comment]
```3. 判断IP是否是已经被保留的IP，并跳转5```
第 3 步“保留的 IP”是指？

**Comment by anrs** [comment]
因为并不能区分 stop/terminate，所以也不能区分```保留```和```占用```吧？所以```判断IP是否已经被占用```这个怎么判断？

**Comment by anrs** [comment]
```
1. 判断是否申请特定IP，是则跳转3
2. 从calico IP池内分配IP，结束
3. 判断IP是否是已经被保留的IP，并跳转5
4. 判断IP是否已经被占用，否则把IP标识为已经被占用，并跳转5，是则抛出异常
5. 分配申请的特定IP
```
按我们讨论的，改成
```
1. 判断是否申请特定 IP，否则 assign a Calico IP
2. Minons IP 状态判断：
        a. not assigned，assign 该 IP，并标记状态为 assigned
        b. assigned，报错返回
        c. no such IP，assign a Calico IP
```

**Comment by nyanpassu** [comment]
> RequestAddress 流程
> 
> ```
> 1. 判断是否申请特定IP，是则跳转3
> 2. 从calico IP池内分配IP，结束
> 3. 判断IP是否是已经被保留的IP，并跳转5
> 4. 判断IP是否已经被占用，否则把IP标识为已经被占用，并跳转5，是则抛出异常
> 5. 分配申请的特定IP
> ```
> 
> 按我们讨论的，改成
> 
> ```
> 1. 判断是否申请特定 IP；是，则跳转到 2；否，则 assign a Calico IP
> 2. Minons IP 状态判断：
>         a. not assigned，则 assign 该 IP，并标记状态为 assigned
>         b. assigned，报错返回
>         c. no such IP，则 assign a Calico IP 并记录到 Minons
> ```

嗯是的。我和Zhichuang讨论了一下，在etcd上不再存是否占用的状态了。Request之后就从etcd上删掉就好。我稍后更新一下。

**Comment by jschwinger23** [comment]
我们的讨论结果确定了三点:

1. container with label 的语义是 `这个容器 stop 的时候不归还 ip 给 pool`
2. `/barrel/address/${ip}` 的语义是 `这个 ip 没有归还 pool 也没有 分配给任何容器`

只要语义准确, 实现就不会有太大问题, 比如 label 为这种语义的话, request addr 的流程就肯定不会和 label 有关;

另外就是实现的时候尽量减少耦合, 比如 barrel 直接调用 calico api 什么的就不是太好, 能避免的尽量避免.

**Comment by CMGS** [comment]
LGTM 
@nyanpassu 整吧

**Comment by nyanpassu** [comment]
> LGTM
> @nyanpassu 整吧

中午和 @jschwinger23 讨论了一下，我觉得还可以加上一个流程。
在container create的时候，检查networking是不是指定了ip。如果有，那么在etcd上记录这个ip将要被申请。
然后当这个ip的所有者释放ip的时候，不归还到calico ip pool里。接着start新的container的时候，ipam把这个ip分配给它。
如果这个ip没有在使用或者没有stop使用者就start了新的container，那么ipam会去calico pool里拿ip（出错或者成功）。

**Comment by jschwinger23** [comment]
> > LGTM
> > @nyanpassu 整吧
> 
> 中午和 @jschwinger23 讨论了一下，我觉得还可以加上一个流程。
> 在container create的时候，检查networking是不是指定了ip。如果有，那么在etcd上记录这个ip将要被申请。
> 然后当这个ip的所有者释放ip的时候，不归还到calico ip pool里。接着start新的container的时候，ipam把这个ip分配给它。
> 如果这个ip没有在使用或者没有stop使用者就start了新的container，那么ipam会去calico pool里拿ip（出错或者成功）。


我主要说的标记 flag 这一步从 CNM Leave 移动到 Barrel, 好处是不依赖旧容器是否有 label, 不过可以做一步看一步.

**Comment by nyanpassu** [comment]
> > > LGTM
> > > @nyanpassu 整吧
> > 
> > 
> > 中午和 @jschwinger23 讨论了一下，我觉得还可以加上一个流程。
> > 在container create的时候，检查networking是不是指定了ip。如果有，那么在etcd上记录这个ip将要被申请。
> > 然后当这个ip的所有者释放ip的时候，不归还到calico ip pool里。接着start新的container的时候，ipam把这个ip分配给它。
> > 如果这个ip没有在使用或者没有stop使用者就start了新的container，那么ipam会去calico pool里拿ip（出错或者成功）。
> 
> 我主要说的标记 flag 这一步从 CNM Leave 移动到 Barrel, 好处是不依赖旧容器是否有 label, 不过可以做一步看一步.

我觉得可以都有呀，不冲突，加一个flag就行。这样docker run也可以用fixed ip。不然就必须按照container create. stop old. start new这样来了。

**Comment by nyanpassu** [comment]
当然docker run实质上也是create start，但是这样我们就对docker cli也兼容了。

**Comment by nyanpassu** [comment]
> > > LGTM
> > > @nyanpassu 整吧
> > 
> > 
> > 中午和 @jschwinger23 讨论了一下，我觉得还可以加上一个流程。
> > 在container create的时候，检查networking是不是指定了ip。如果有，那么在etcd上记录这个ip将要被申请。
> > 然后当这个ip的所有者释放ip的时候，不归还到calico ip pool里。接着start新的container的时候，ipam把这个ip分配给它。
> > 如果这个ip没有在使用或者没有stop使用者就start了新的container，那么ipam会去calico pool里拿ip（出错或者成功）。
> 
> 我主要说的标记 flag 这一步从 CNM Leave 移动到 Barrel, 好处是不依赖旧容器是否有 label, 不过可以做一步看一步.

我觉得可以都有呀，不冲突，加一个flag就行。这样先stop old也可以继续继承ip。

**Comment by nyanpassu** [comment]
> 中午和 @jschwinger23 讨论了一下，我觉得还可以加上一个流程。
> 在container create的时候，检查networking是不是指定了ip。如果有，那么在etcd上记录这个ip将要被申请。
> 然后当这个ip的所有者释放ip的时候，不归还到calico ip pool里。接着start新的container的时候，ipam把这个ip分配给它。
> 如果这个ip没有在使用或者没有stop使用者就start了新的container，那么ipam会去calico pool里拿ip（出错或者成功）。

@anrs anders觉得怎么样
